import { Router, type IRouter } from "express";
import healthRouter from "./health";
import analyzeFoodRouter from "./analyzeFood";
import mealsRouter from "./meals";
import profileRouter from "./profile";
import storageRouter from "./storageRoutes";
import weightRouter from "./weight";
import notificationsRouter from "./notifications";
import foodsRouter from "./foods";
import vitalityRouter from "./vitality";
import leaderboardRouter from "./leaderboard";
import challengesRouter from "./challenges";
import userStatsRouter from "./userStats";
import agentRouter from "./agent";
import partnersRouter from "./partners";
import searchNearbyRouter from "./searchNearby";
import supplementRecommendRouter from "./supplementRecommend";
import healthFlagsRouter from "./healthFlags";
import communityRouter from "./community";
import savedFoodsRouter from "./savedFoods";
import mealTemplatesRouter from "./mealTemplates";
import caloriesBurnedRouter from "./caloriesBurned";
import exerciseLogsRouter from "./exerciseLogs";
import exerciseEstimateRouter from "./exerciseEstimate";

const router: IRouter = Router();

router.use(healthRouter);
router.use(analyzeFoodRouter);
router.use(foodsRouter);
router.use(mealsRouter);
router.use(profileRouter);
router.use(storageRouter);
router.use(weightRouter);
router.use(notificationsRouter);
router.use(vitalityRouter);
router.use(leaderboardRouter);
router.use(challengesRouter);
router.use(userStatsRouter);
router.use(agentRouter);
router.use(partnersRouter);
router.use(searchNearbyRouter);
router.use(supplementRecommendRouter);
router.use(healthFlagsRouter);
router.use(communityRouter);
router.use(savedFoodsRouter);
router.use(mealTemplatesRouter);
router.use(caloriesBurnedRouter);
router.use(exerciseLogsRouter);
router.use(exerciseEstimateRouter);

export default router;
